server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jcu_gym?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: cz519826
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

    #email config
    mail:
      host: smtp.gmail.com
      port: 587
      username: chenxingjian.14905947@gmail.com
      password: echkofnuisdvcngp
      protocol: smtp
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

mybatis-plus:
  # mapper.xml 的路径（如果有使用 XML 的话）
  mapper-locations: classpath*:mapper/*.xml
  # 实体类所在的包
  type-aliases-package: com.example.demo.model
  global-config:
    db-config:
      id-type: auto  # 主键策略（auto | input | id_worker | uuid）
      logic-delete-value: 1  # 逻辑已删除值
      logic-not-delete-value: 0  # 逻辑未删除值
  configuration:
    map-underscore-to-camel-case: true  # 下划线转驼峰

#log config
logging:
  level:
    com.baomidou.mybatisplus: debug
    com.example.demo.mapper: debug
